# Generated by Django 5.2.14 on 2026-05-14 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RingSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ring', models.TextField()),
                ('board_pair', models.TextField()),
                ('link_instance', models.TextField(blank=True)),
                ('peak_time', models.TextField(blank=True)),
                ('endpoint_1', models.TextField(blank=True)),
                ('tx_1_gbps', models.FloatField(default=0)),
                ('endpoint_2', models.TextField(blank=True)),
                ('tx_2_gbps', models.FloatField(default=0)),
                ('total_tx_gbps', models.FloatField(default=0)),
                ('avg_endpoint_1_gbps', models.FloatField(default=0)),
                ('avg_endpoint_2_gbps', models.FloatField(default=0)),
                ('total_avg_gbps', models.FloatField(default=0)),
                ('peak_average_ratio', models.FloatField(default=0)),
                ('max_capacity_gbps', models.FloatField(default=0)),
                ('util_percent', models.FloatField(default=0)),
                ('util_band', models.CharField(blank=True, max_length=50)),
                ('upload_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ring_summaries', to='dashboard.uploadrun')),
            ],
        ),
        migrations.CreateModel(
            name='Link100GSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.TextField()),
                ('source_site', models.TextField(blank=True)),
                ('sink_site', models.TextField(blank=True)),
                ('peak_time', models.TextField(blank=True)),
                ('peak_util_gbps', models.FloatField(default=0)),
                ('average_util_gbps', models.FloatField(default=0)),
                ('peak_average_ratio', models.FloatField(default=0)),
                ('util_band', models.CharField(blank=True, max_length=50)),
                ('upload_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link100g_summaries', to='dashboard.uploadrun')),
            ],
        ),
    ]
