# Generated by Django 5.2.14 on 2026-05-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RingNodeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_group_name', models.CharField(max_length=255)),
                ('normalized_ring', models.CharField(db_index=True, max_length=255)),
                ('board_pair', models.CharField(blank=True, max_length=100)),
                ('normalized_board_pair', models.CharField(db_index=True, max_length=100)),
                ('source_ne', models.CharField(max_length=255)),
                ('sink_ne', models.CharField(max_length=255)),
            ],
        ),
    ]
