# Generated by Django 5.2.15 on 2026-06-30 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_ringnodemapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='FTTHSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olt_name', models.CharField(max_length=255)),
                ('peak_time', models.DateTimeField()),
                ('peak_util_gbps', models.FloatField()),
                ('average_util_gbps', models.FloatField()),
                ('peak_direction', models.CharField(max_length=10)),
                ('upload_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ftth_summaries', to='dashboard.uploadrun')),
            ],
            options={
                'ordering': ['-peak_util_gbps'],
            },
        ),
    ]
