# Generated by Django 5.2.15 on 2026-07-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_ftthsummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ftthsummary',
            name='peak_time',
            field=models.TextField(blank=True),
        ),
    ]
