# Generated by Django 5.2.15 on 2026-07-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_ftthsummary_peak_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessBandwidth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neid', models.CharField(max_length=100)),
                ('site_id', models.CharField(max_length=100)),
                ('site_name', models.CharField(max_length=255, unique=True)),
                ('current_capacity_mbps', models.FloatField(default=0)),
                ('current_capacity_gbps', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['site_name'],
            },
        ),
    ]
