# Generated by Django 5.2.15 on 2026-07-05 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_accessbandwidth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessbandwidth',
            old_name='current_capacity_gbps',
            new_name='current_capacity',
        ),
        migrations.RemoveField(
            model_name='accessbandwidth',
            name='current_capacity_mbps',
        ),
    ]
